---
title: Visualização de Dados
author: Luiz Fernando
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

```{r message=FALSE, warning=FALSE, echo=FALSE}
options(scipen=999999)
```

### Quero saber

Quantos morreram por país na 1ª Guerra Mundial?


### Dados

Os dados foram encontrados no site **EM**: [A Primeira Guerra Mundial em números](https://www.em.com.br/app/noticia/internacional/2014/06/28/interna_internacional,542894/a-primeira-guerra-mundial-em-numeros.shtml)


### Base de dados

```{r}
paises <- c(
  "França",
  "Alemanha",
  "Áustria-Hungria",
  "Rússia",
  "Grã-Bretanha",
  "Itália",
  "Império Otomano",
  "Sérvia"
  )

mortes <- c(1400000, 2000000, 1400000, 2000000, 960000, 600000, 800000, 130000)
```


### Gráfico

```{r message=FALSE, warning=FALSE}
library(dplyr)

barplot(
  mortes,
  col = "#9c171f",
  cex.axis = 0.75,
  main = "Número de mortes por países na 1ª Guerra Mundial",
  ylab = "Número de mortes",
  xaxt="n",
  sub = "Fonte: Jornal Estado de Minas"
) %>% 
  text(labels = paises, 
       par("usr")[3],
       srt = 45, 
       adj = c(1,1), 
       xpd = TRUE, 
       cex = 0.75
  )
```

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=FALSE}
library(ggplot2)
```

```{r, echo=FALSE, eval=FALSE}
base <- tibble(paises, mortes)

base %>% 
  ggplot(aes(x = paises, y = mortes)) +
  geom_bar(stat = 'identity', fill = "#9c171f") +
  #geom_text(aes(label = mortos), hjust = 0, color = "#727070") + 
  coord_flip() +
  scale_y_continuous(limits = c(0, 2200000)) +
  theme_minimal() +
  labs(y = "Número de mortes", x = "", title = "Número de mortes por países na 1ª Guerra Mundial")
  
```

